namespace ToDo.Migrations
{
	using Core;
	using Models;
	using System;
	using System.Collections.Generic;
	using System.Data.Entity.Migrations;
	using System.Linq;

	internal sealed class Configuration : DbMigrationsConfiguration<ApplicationDbContext>
	{
		public Configuration()
		{
			AutomaticMigrationsEnabled = true;
		}

		protected override void Seed(ApplicationDbContext context)
		{
			var colors = new List<ColorClass> {
				new ColorClass { Name = "Текущее", Value = "active" },
				new ColorClass { Name = "Готово", Value = "success" },
				new ColorClass { Name = "Сведения", Value = "info" },
				new ColorClass { Name = "Внимание", Value = "warning" },
				new ColorClass { Name = "Опасность", Value = "danger" }
			};
			colors.ForEach(s => context.ColorClasses.AddOrUpdate(p => p.Name, s));
			context.SaveChanges();

			var icons = new List<IconClass> {
				new IconClass { Name = "asterisk", Value = "glyphicon glyphicon-asterisk" },
				new IconClass { Name = "plus", Value = "glyphicon glyphicon-plus" },
				new IconClass { Name = "euro", Value = "glyphicon glyphicon-euro" },
				new IconClass { Name = "eur", Value = "glyphicon glyphicon-eur" },
				new IconClass { Name = "minus", Value = "glyphicon glyphicon-minus" },
				new IconClass { Name = "cloud", Value = "glyphicon glyphicon-cloud" },
				new IconClass { Name = "envelope", Value = "glyphicon glyphicon-envelope" },
				new IconClass { Name = "pencil", Value = "glyphicon glyphicon-pencil" },
				new IconClass { Name = "glass", Value = "glyphicon glyphicon-glass" },
				new IconClass { Name = "music", Value = "glyphicon glyphicon-music" },
				new IconClass { Name = "search", Value = "glyphicon glyphicon-search" },
				new IconClass { Name = "heart", Value = "glyphicon glyphicon-heart" },
				new IconClass { Name = "star", Value = "glyphicon glyphicon-star" },
				new IconClass { Name = "star-empty", Value = "glyphicon glyphicon-star-empty" },
				new IconClass { Name = "user", Value = "glyphicon glyphicon-user" },
				new IconClass { Name = "film", Value = "glyphicon glyphicon-film" },
				new IconClass { Name = "th-large", Value = "glyphicon glyphicon-th-large" },
				new IconClass { Name = "th", Value = "glyphicon glyphicon-th" },
				new IconClass { Name = "th-list", Value = "glyphicon glyphicon-th-list" },
				new IconClass { Name = "ok", Value = "glyphicon glyphicon-ok" },
				new IconClass { Name = "remove", Value = "glyphicon glyphicon-remove" },
				new IconClass { Name = "zoom-in", Value = "glyphicon glyphicon-zoom-in" },
				new IconClass { Name = "zoom-out", Value = "glyphicon glyphicon-zoom-out" },
				new IconClass { Name = "off", Value = "glyphicon glyphicon-off" },
				new IconClass { Name = "signal", Value = "glyphicon glyphicon-signal" },
				new IconClass { Name = "cog", Value = "glyphicon glyphicon-cog" },
				new IconClass { Name = "trash", Value = "glyphicon glyphicon-trash" },
				new IconClass { Name = "home", Value = "glyphicon glyphicon-home" },
				new IconClass { Name = "file", Value = "glyphicon glyphicon-file" },
				new IconClass { Name = "time", Value = "glyphicon glyphicon-time" },
				new IconClass { Name = "road", Value = "glyphicon glyphicon-road" },
				new IconClass { Name = "download-alt", Value = "glyphicon glyphicon-download-alt" },
				new IconClass { Name = "download", Value = "glyphicon glyphicon-download" },
				new IconClass { Name = "upload", Value = "glyphicon glyphicon-upload" },
				new IconClass { Name = "inbox", Value = "glyphicon glyphicon-inbox" },
				new IconClass { Name = "play-circle", Value = "glyphicon glyphicon-play-circle" },
				new IconClass { Name = "repeat", Value = "glyphicon glyphicon-repeat" },
				new IconClass { Name = "refresh", Value = "glyphicon glyphicon-refresh" },
				new IconClass { Name = "list-alt", Value = "glyphicon glyphicon-list-alt" },
				new IconClass { Name = "lock", Value = "glyphicon glyphicon-lock" },
				new IconClass { Name = "flag", Value = "glyphicon glyphicon-flag" },
				new IconClass { Name = "headphones", Value = "glyphicon glyphicon-headphones" },
				new IconClass { Name = "volume-off", Value = "glyphicon glyphicon-volume-off" },
				new IconClass { Name = "volume-down", Value = "glyphicon glyphicon-volume-down" },
				new IconClass { Name = "volume-up", Value = "glyphicon glyphicon-volume-up" },
				new IconClass { Name = "qrcode", Value = "glyphicon glyphicon-qrcode" },
				new IconClass { Name = "barcode", Value = "glyphicon glyphicon-barcode" },
				new IconClass { Name = "tag", Value = "glyphicon glyphicon-tag" },
				new IconClass { Name = "tags", Value = "glyphicon glyphicon-tags" },
				new IconClass { Name = "book", Value = "glyphicon glyphicon-book" },
				new IconClass { Name = "bookmark", Value = "glyphicon glyphicon-bookmark" },
				new IconClass { Name = "print", Value = "glyphicon glyphicon-print" },
				new IconClass { Name = "camera", Value = "glyphicon glyphicon-camera" },
				new IconClass { Name = "font", Value = "glyphicon glyphicon-font" },
				new IconClass { Name = "bold", Value = "glyphicon glyphicon-bold" },
				new IconClass { Name = "italic", Value = "glyphicon glyphicon-italic" },
				new IconClass { Name = "text-height", Value = "glyphicon glyphicon-text-height" },
				new IconClass { Name = "text-width", Value = "glyphicon glyphicon-text-width" },
				new IconClass { Name = "align-left", Value = "glyphicon glyphicon-align-left" },
				new IconClass { Name = "align-center", Value = "glyphicon glyphicon-align-center" },
				new IconClass { Name = "align-right", Value = "glyphicon glyphicon-align-right" },
				new IconClass { Name = "align-justify", Value = "glyphicon glyphicon-align-justify" },
				new IconClass { Name = "list", Value = "glyphicon glyphicon-list" },
				new IconClass { Name = "indent-left", Value = "glyphicon glyphicon-indent-left" },
				new IconClass { Name = "indent-right", Value = "glyphicon glyphicon-indent-right" },
				new IconClass { Name = "facetime-video", Value = "glyphicon glyphicon-facetime-video" },
				new IconClass { Name = "picture", Value = "glyphicon glyphicon-picture" },
				new IconClass { Name = "map-marker", Value = "glyphicon glyphicon-map-marker" },
				new IconClass { Name = "adjust", Value = "glyphicon glyphicon-adjust" },
				new IconClass { Name = "tint", Value = "glyphicon glyphicon-tint" },
				new IconClass { Name = "edit", Value = "glyphicon glyphicon-edit" },
				new IconClass { Name = "share", Value = "glyphicon glyphicon-share" },
				new IconClass { Name = "check", Value = "glyphicon glyphicon-check" },
				new IconClass { Name = "move", Value = "glyphicon glyphicon-move" },
				new IconClass { Name = "step-backward", Value = "glyphicon glyphicon-step-backward" },
				new IconClass { Name = "fast-backward", Value = "glyphicon glyphicon-fast-backward" },
				new IconClass { Name = "backward", Value = "glyphicon glyphicon-backward" },
				new IconClass { Name = "play", Value = "glyphicon glyphicon-play" },
				new IconClass { Name = "pause", Value = "glyphicon glyphicon-pause" },
				new IconClass { Name = "stop", Value = "glyphicon glyphicon-stop" },
				new IconClass { Name = "forward", Value = "glyphicon glyphicon-forward" },
				new IconClass { Name = "fast-forward", Value = "glyphicon glyphicon-fast-forward" },
				new IconClass { Name = "step-forward", Value = "glyphicon glyphicon-step-forward" },
				new IconClass { Name = "eject", Value = "glyphicon glyphicon-eject" },
				new IconClass { Name = "chevron-left", Value = "glyphicon glyphicon-chevron-left" },
				new IconClass { Name = "chevron-right", Value = "glyphicon glyphicon-chevron-right" },
				new IconClass { Name = "plus-sign", Value = "glyphicon glyphicon-plus-sign" },
				new IconClass { Name = "minus-sign", Value = "glyphicon glyphicon-minus-sign" },
				new IconClass { Name = "remove-sign", Value = "glyphicon glyphicon-remove-sign" },
				new IconClass { Name = "ok-sign", Value = "glyphicon glyphicon-ok-sign" },
				new IconClass { Name = "question-sign", Value = "glyphicon glyphicon-question-sign" },
				new IconClass { Name = "info-sign", Value = "glyphicon glyphicon-info-sign" },
				new IconClass { Name = "screenshot", Value = "glyphicon glyphicon-screenshot" },
				new IconClass { Name = "remove-circle", Value = "glyphicon glyphicon-remove-circle" },
				new IconClass { Name = "ok-circle", Value = "glyphicon glyphicon-ok-circle" },
				new IconClass { Name = "ban-circle", Value = "glyphicon glyphicon-ban-circle" },
				new IconClass { Name = "arrow-left", Value = "glyphicon glyphicon-arrow-left" },
				new IconClass { Name = "arrow-right", Value = "glyphicon glyphicon-arrow-right" },
				new IconClass { Name = "arrow-up", Value = "glyphicon glyphicon-arrow-up" },
				new IconClass { Name = "arrow-down", Value = "glyphicon glyphicon-arrow-down" },
				new IconClass { Name = "share-alt", Value = "glyphicon glyphicon-share-alt" },
				new IconClass { Name = "resize-full", Value = "glyphicon glyphicon-resize-full" },
				new IconClass { Name = "resize-small", Value = "glyphicon glyphicon-resize-small" },
				new IconClass { Name = "exclamation-sign", Value = "glyphicon glyphicon-exclamation-sign" },
				new IconClass { Name = "gift", Value = "glyphicon glyphicon-gift" },
				new IconClass { Name = "leaf", Value = "glyphicon glyphicon-leaf" },
				new IconClass { Name = "fire", Value = "glyphicon glyphicon-fire" },
				new IconClass { Name = "eye-open", Value = "glyphicon glyphicon-eye-open" },
				new IconClass { Name = "eye-close", Value = "glyphicon glyphicon-eye-close" },
				new IconClass { Name = "warning-sign", Value = "glyphicon glyphicon-warning-sign" },
				new IconClass { Name = "plane", Value = "glyphicon glyphicon-plane" },
				new IconClass { Name = "calendar", Value = "glyphicon glyphicon-calendar" },
				new IconClass { Name = "random", Value = "glyphicon glyphicon-random" },
				new IconClass { Name = "comment", Value = "glyphicon glyphicon-comment" },
				new IconClass { Name = "magnet", Value = "glyphicon glyphicon-magnet" },
				new IconClass { Name = "chevron-up", Value = "glyphicon glyphicon-chevron-up" },
				new IconClass { Name = "chevron-down", Value = "glyphicon glyphicon-chevron-down" },
				new IconClass { Name = "retweet", Value = "glyphicon glyphicon-retweet" },
				new IconClass { Name = "shopping-cart", Value = "glyphicon glyphicon-shopping-cart" },
				new IconClass { Name = "folder-close", Value = "glyphicon glyphicon-folder-close" },
				new IconClass { Name = "folder-open", Value = "glyphicon glyphicon-folder-open" },
				new IconClass { Name = "resize-vertical", Value = "glyphicon glyphicon-resize-vertical" },
				new IconClass { Name = "resize-horizontal", Value = "glyphicon glyphicon-resize-horizontal" },
				new IconClass { Name = "hdd", Value = "glyphicon glyphicon-hdd" },
				new IconClass { Name = "bullhorn", Value = "glyphicon glyphicon-bullhorn" },
				new IconClass { Name = "bell", Value = "glyphicon glyphicon-bell" },
				new IconClass { Name = "certificate", Value = "glyphicon glyphicon-certificate" },
				new IconClass { Name = "thumbs-up", Value = "glyphicon glyphicon-thumbs-up" },
				new IconClass { Name = "thumbs-down", Value = "glyphicon glyphicon-thumbs-down" },
				new IconClass { Name = "hand-right", Value = "glyphicon glyphicon-hand-right" },
				new IconClass { Name = "hand-left", Value = "glyphicon glyphicon-hand-left" },
				new IconClass { Name = "hand-up", Value = "glyphicon glyphicon-hand-up" },
				new IconClass { Name = "hand-down", Value = "glyphicon glyphicon-hand-down" },
				new IconClass { Name = "circle-arrow-right", Value = "glyphicon glyphicon-circle-arrow-right" },
				new IconClass { Name = "circle-arrow-left", Value = "glyphicon glyphicon-circle-arrow-left" },
				new IconClass { Name = "circle-arrow-up", Value = "glyphicon glyphicon-circle-arrow-up" },
				new IconClass { Name = "circle-arrow-down", Value = "glyphicon glyphicon-circle-arrow-down" },
				new IconClass { Name = "globe", Value = "glyphicon glyphicon-globe" },
				new IconClass { Name = "wrench", Value = "glyphicon glyphicon-wrench" },
				new IconClass { Name = "tasks", Value = "glyphicon glyphicon-tasks" },
				new IconClass { Name = "filter", Value = "glyphicon glyphicon-filter" },
				new IconClass { Name = "briefcase", Value = "glyphicon glyphicon-briefcase" },
				new IconClass { Name = "fullscreen", Value = "glyphicon glyphicon-fullscreen" },
				new IconClass { Name = "dashboard", Value = "glyphicon glyphicon-dashboard" },
				new IconClass { Name = "paperclip", Value = "glyphicon glyphicon-paperclip" },
				new IconClass { Name = "heart-empty", Value = "glyphicon glyphicon-heart-empty" },
				new IconClass { Name = "link", Value = "glyphicon glyphicon-link" },
				new IconClass { Name = "phone", Value = "glyphicon glyphicon-phone" },
				new IconClass { Name = "pushpin", Value = "glyphicon glyphicon-pushpin" },
				new IconClass { Name = "usd", Value = "glyphicon glyphicon-usd" },
				new IconClass { Name = "gbp", Value = "glyphicon glyphicon-gbp" },
				new IconClass { Name = "sort", Value = "glyphicon glyphicon-sort" },
				new IconClass { Name = "sort-by-alphabet", Value = "glyphicon glyphicon-sort-by-alphabet" },
				new IconClass { Name = "sort-by-alphabet-alt", Value = "glyphicon glyphicon-sort-by-alphabet-alt" },
				new IconClass { Name = "sort-by-order", Value = "glyphicon glyphicon-sort-by-order" },
				new IconClass { Name = "sort-by-order-alt", Value = "glyphicon glyphicon-sort-by-order-alt" },
				new IconClass { Name = "sort-by-attributes", Value = "glyphicon glyphicon-sort-by-attributes" },
				new IconClass { Name = "sort-by-attributes-alt", Value = "glyphicon glyphicon-sort-by-attributes-alt" },
				new IconClass { Name = "unchecked", Value = "glyphicon glyphicon-unchecked" },
				new IconClass { Name = "expand", Value = "glyphicon glyphicon-expand" },
				new IconClass { Name = "collapse-down", Value = "glyphicon glyphicon-collapse-down" },
				new IconClass { Name = "collapse-up", Value = "glyphicon glyphicon-collapse-up" },
				new IconClass { Name = "log-in", Value = "glyphicon glyphicon-log-in" },
				new IconClass { Name = "flash", Value = "glyphicon glyphicon-flash" },
				new IconClass { Name = "log-out", Value = "glyphicon glyphicon-log-out" },
				new IconClass { Name = "new-window", Value = "glyphicon glyphicon-new-window" },
				new IconClass { Name = "record", Value = "glyphicon glyphicon-record" },
				new IconClass { Name = "save", Value = "glyphicon glyphicon-save" },
				new IconClass { Name = "open", Value = "glyphicon glyphicon-open" },
				new IconClass { Name = "saved", Value = "glyphicon glyphicon-saved" },
				new IconClass { Name = "import", Value = "glyphicon glyphicon-import" },
				new IconClass { Name = "export", Value = "glyphicon glyphicon-export" },
				new IconClass { Name = "send", Value = "glyphicon glyphicon-send" },
				new IconClass { Name = "floppy-disk", Value = "glyphicon glyphicon-floppy-disk" },
				new IconClass { Name = "floppy-saved", Value = "glyphicon glyphicon-floppy-saved" },
				new IconClass { Name = "floppy-remove", Value = "glyphicon glyphicon-floppy-remove" },
				new IconClass { Name = "floppy-save", Value = "glyphicon glyphicon-floppy-save" },
				new IconClass { Name = "floppy-open", Value = "glyphicon glyphicon-floppy-open" },
				new IconClass { Name = "credit-card", Value = "glyphicon glyphicon-credit-card" },
				new IconClass { Name = "transfer", Value = "glyphicon glyphicon-transfer" },
				new IconClass { Name = "cutlery", Value = "glyphicon glyphicon-cutlery" },
				new IconClass { Name = "header", Value = "glyphicon glyphicon-header" },
				new IconClass { Name = "compressed", Value = "glyphicon glyphicon-compressed" },
				new IconClass { Name = "earphone", Value = "glyphicon glyphicon-earphone" },
				new IconClass { Name = "phone-alt", Value = "glyphicon glyphicon-phone-alt" },
				new IconClass { Name = "tower", Value = "glyphicon glyphicon-tower" },
				new IconClass { Name = "stats", Value = "glyphicon glyphicon-stats" },
				new IconClass { Name = "sd-video", Value = "glyphicon glyphicon-sd-video" },
				new IconClass { Name = "hd-video", Value = "glyphicon glyphicon-hd-video" },
				new IconClass { Name = "subtitles", Value = "glyphicon glyphicon-subtitles" },
				new IconClass { Name = "sound-stereo", Value = "glyphicon glyphicon-sound-stereo" },
				new IconClass { Name = "sound-dolby", Value = "glyphicon glyphicon-sound-dolby" },
				new IconClass { Name = "sound-5-1", Value = "glyphicon glyphicon-sound-5-1" },
				new IconClass { Name = "sound-6-1", Value = "glyphicon glyphicon-sound-6-1" },
				new IconClass { Name = "sound-7-1", Value = "glyphicon glyphicon-sound-7-1" },
				new IconClass { Name = "copyright-mark", Value = "glyphicon glyphicon-copyright-mark" },
				new IconClass { Name = "registration-mark", Value = "glyphicon glyphicon-registration-mark" },
				new IconClass { Name = "cloud-download", Value = "glyphicon glyphicon-cloud-download" },
				new IconClass { Name = "cloud-upload", Value = "glyphicon glyphicon-cloud-upload" },
				new IconClass { Name = "tree-conifer", Value = "glyphicon glyphicon-tree-conifer" },
				new IconClass { Name = "tree-deciduous", Value = "glyphicon glyphicon-tree-deciduous" },
				new IconClass { Name = "cd", Value = "glyphicon glyphicon-cd" },
				new IconClass { Name = "save-file", Value = "glyphicon glyphicon-save-file" },
				new IconClass { Name = "open-file", Value = "glyphicon glyphicon-open-file" },
				new IconClass { Name = "level-up", Value = "glyphicon glyphicon-level-up" },
				new IconClass { Name = "copy", Value = "glyphicon glyphicon-copy" },
				new IconClass { Name = "paste", Value = "glyphicon glyphicon-paste" },
				new IconClass { Name = "alert", Value = "glyphicon glyphicon-alert" },
				new IconClass { Name = "equalizer", Value = "glyphicon glyphicon-equalizer" },
				new IconClass { Name = "king", Value = "glyphicon glyphicon-king" },
				new IconClass { Name = "queen", Value = "glyphicon glyphicon-queen" },
				new IconClass { Name = "pawn", Value = "glyphicon glyphicon-pawn" },
				new IconClass { Name = "bishop", Value = "glyphicon glyphicon-bishop" },
				new IconClass { Name = "knight", Value = "glyphicon glyphicon-knight" },
				new IconClass { Name = "baby-formula", Value = "glyphicon glyphicon-baby-formula" },
				new IconClass { Name = "tent", Value = "glyphicon glyphicon-tent" },
				new IconClass { Name = "blackboard", Value = "glyphicon glyphicon-blackboard" },
				new IconClass { Name = "bed", Value = "glyphicon glyphicon-bed" },
				new IconClass { Name = "apple", Value = "glyphicon glyphicon-apple" },
				new IconClass { Name = "erase", Value = "glyphicon glyphicon-erase" },
				new IconClass { Name = "hourglass", Value = "glyphicon glyphicon-hourglass" },
				new IconClass { Name = "lamp", Value = "glyphicon glyphicon-lamp" },
				new IconClass { Name = "duplicate", Value = "glyphicon glyphicon-duplicate" },
				new IconClass { Name = "piggy-bank", Value = "glyphicon glyphicon-piggy-bank" },
				new IconClass { Name = "scissors", Value = "glyphicon glyphicon-scissors" },
				new IconClass { Name = "bitcoin", Value = "glyphicon glyphicon-bitcoin" },
				new IconClass { Name = "btc", Value = "glyphicon glyphicon-btc" },
				new IconClass { Name = "xbt", Value = "glyphicon glyphicon-xbt" },
				new IconClass { Name = "yen", Value = "glyphicon glyphicon-yen" },
				new IconClass { Name = "jpy", Value = "glyphicon glyphicon-jpy" },
				new IconClass { Name = "ruble", Value = "glyphicon glyphicon-ruble" },
				new IconClass { Name = "rub", Value = "glyphicon glyphicon-rub" },
				new IconClass { Name = "scale", Value = "glyphicon glyphicon-scale" },
				new IconClass { Name = "ice-lolly", Value = "glyphicon glyphicon-ice-lolly" },
				new IconClass { Name = "ice-lolly-tasted", Value = "glyphicon glyphicon-ice-lolly-tasted" },
				new IconClass { Name = "education", Value = "glyphicon glyphicon-education" },
				new IconClass { Name = "option-horizontal", Value = "glyphicon glyphicon-option-horizontal" },
				new IconClass { Name = "option-vertical", Value = "glyphicon glyphicon-option-vertical" },
				new IconClass { Name = "menu-hamburger", Value = "glyphicon glyphicon-menu-hamburger" },
				new IconClass { Name = "modal-window", Value = "glyphicon glyphicon-modal-window" },
				new IconClass { Name = "oil", Value = "glyphicon glyphicon-oil" },
				new IconClass { Name = "grain", Value = "glyphicon glyphicon-grain" },
				new IconClass { Name = "sunglasses", Value = "glyphicon glyphicon-sunglasses" },
				new IconClass { Name = "text-size", Value = "glyphicon glyphicon-text-size" },
				new IconClass { Name = "text-color", Value = "glyphicon glyphicon-text-color" },
				new IconClass { Name = "text-background", Value = "glyphicon glyphicon-text-background" },
				new IconClass { Name = "object-align-top", Value = "glyphicon glyphicon-object-align-top" },
				new IconClass { Name = "object-align-bottom", Value = "glyphicon glyphicon-object-align-bottom" },
				new IconClass { Name = "object-align-horizontal", Value = "glyphicon glyphicon-object-align-horizontal" },
				new IconClass { Name = "object-align-left", Value = "glyphicon glyphicon-object-align-left" },
				new IconClass { Name = "object-align-vertical", Value = "glyphicon glyphicon-object-align-vertical" },
				new IconClass { Name = "object-align-right", Value = "glyphicon glyphicon-object-align-right" },
				new IconClass { Name = "triangle-right", Value = "glyphicon glyphicon-triangle-right" },
				new IconClass { Name = "triangle-left", Value = "glyphicon glyphicon-triangle-left" },
				new IconClass { Name = "triangle-bottom", Value = "glyphicon glyphicon-triangle-bottom" },
				new IconClass { Name = "triangle-top", Value = "glyphicon glyphicon-triangle-top" },
				new IconClass { Name = "console", Value = "glyphicon glyphicon-console" },
				new IconClass { Name = "superscript", Value = "glyphicon glyphicon-superscript" },
				new IconClass { Name = "subscript", Value = "glyphicon glyphicon-subscript" },
				new IconClass { Name = "menu-left", Value = "glyphicon glyphicon-menu-left" },
				new IconClass { Name = "menu-right", Value = "glyphicon glyphicon-menu-right" },
				new IconClass { Name = "menu-down", Value = "glyphicon glyphicon-menu-down" },
				new IconClass { Name = "menu-up", Value = "glyphicon glyphicon-menu-up" }
			};
			icons.ForEach(s => context.IconClasses.AddOrUpdate(p => p.Name, s));
			context.SaveChanges();

			//var states = new List<State> {
			//	new State {
			//		Name = "Запланировано",
			//		Value = "planned",
			//		IconClassId = icons.Single(s => s.Name == "exclamation-sign").Id,
			//		ColorClassId = colors.Single(s => s.Value == "warning").Id,
			//	},
			//	new State {
			//		Name = "В работе",
			//		Value = "run",
			//		IconClassId = icons.Single(s => s.Name == "refresh").Id,
			//		ColorClassId = colors.Single(s => s.Value == "active").Id,
			//	},
			//	new State {
			//		Name = "Выполнено",
			//		Value = "done",
			//		IconClassId = icons.Single(s => s.Name == "ok").Id,
			//		ColorClassId = colors.Single(s => s.Value == "success").Id,
			//	},
			//};
			//states.ForEach(s => context.States.AddOrUpdate(p => p.Name, s));
			//context.SaveChanges();
		}
	}
}